sudo: required
services:
  - docker

before_install:
  - docker build -t invincible0305/docker-react  -f Dockerfile.dev .

script:
  - docker run invincible0305/docker-react npm run test -- --coverage
